-- Run this once in the Supabase SQL Editor (Dashboard -> SQL Editor -> New query)
-- to set up the trips table and move the 3 built-in trips into it.

create table if not exists public.trips (
  id bigint generated by default as identity primary key,
  destination text not null,
  start_date date not null,
  end_date date not null,
  description text not null default '',
  activities text[] not null default '{}',
  packing_list text[],
  notes text,
  budget numeric not null,
  spent numeric not null default 0,
  travel_style text not null,
  image text not null
);

alter table public.trips enable row level security;

-- Trip info isn't sensitive like subscriber emails, so it's fine for
-- anyone (including the anon key used in the browser) to read it.
-- No insert/update/delete policy for anon -- only the service-role admin
-- client could write here later, same pattern as subscribers.
create policy "Allow public read access"
  on public.trips
  for select
  to anon
  using (true);

-- Move the 3 built-in trips from src/lib/trips.ts into the table, keeping
-- their existing ids so links like /trips/1 keep working.
insert into public.trips
  (id, destination, start_date, end_date, description, activities, budget, spent, travel_style, image)
overriding system value
values
  (1, 'Lisbon, Portugal', '2026-10-12', '2026-10-19',
   'Cobbled streets, vintage trams and pastéis de nata — a slow week wandering the Alfama hills.',
   array['Walking tour', 'Belem Tower', 'Day trip to Sintra'],
   1200, 300, 'City break', '/images/trip-lisbon.jpg'),

  (2, 'Kyoto, Japan', '2027-03-02', '2027-03-10',
   'Vermilion shrine gates, a quiet tea ceremony and a walk through the Arashiyama bamboo grove.',
   array['Fushimi Inari shrine', 'Tea ceremony', 'Bamboo grove hike'],
   2800, 500, 'Culture', '/images/trip-kyoto.jpg'),

  (3, 'Cape Town, South Africa', '2027-01-15', '2027-01-22',
   'Table Mountain views, penguins at Boulders Beach and an afternoon of Cape wine tasting.',
   array['Table Mountain', 'Boulders Beach penguins', 'Wine tasting'],
   2100, 400, 'Adventure', '/images/trip-capetown.jpg')
on conflict (id) do nothing;

-- So the next trip added (id 4) doesn't collide with these manual ids.
select setval(pg_get_serial_sequence('public.trips', 'id'), 3, true);
